// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Swapi$AsyncAwait = require("./Swapi.bs.js");

function go(param) {
  console.log("Let's look at some Star Wars Stuff");
  return Swapi$AsyncAwait.getPerson(/* () */0).then((function (person) {
                console.log("Look at this person:", person);
                console.log("Let's get their planet using this URL:", person.homeworld);
                return Swapi$AsyncAwait.getPlanetFromUrl(person.homeworld).then((function (homeworld) {
                              console.log("And here is their homeworld:", homeworld.name);
                              return Promise.resolve(/* () */0);
                            }));
              }));
}

go(/* () */0);

exports.go = go;
/*  Not a pure module */
